//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiemTapHoa_WebNangCao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangLuong
    {
        public BangLuong(int maBL, int? maNV, int thang, int nam, double? luong, int soNgayNghi, int tongSoNgay)
        {
            MaBL = maBL;
            MaNV = maNV;
            Thang = thang;
            Nam = nam;
            Luong = luong;
            SoNgayNghi = soNgayNghi;
            TongSoNgay = tongSoNgay;
        }

        public int MaBL { get; set; }
        public Nullable<int> MaNV { get; set; }
        public int Thang { get; set; }
        public int Nam { get; set; }
        public Nullable<double> Luong { get; set; }
        public int SoNgayNghi { get; set; }
        public int TongSoNgay { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
